[
  "开篇词",
  "给你 5 个学习 Nest 的理由，你会心动么",
  "快速掌握 Nest CLI",
  "5 种 HTTP 数据传输方式",
  "IOC 解决了什么痛点问题？",
  "如何调试 Nest 项目",
  "使用多种 Provider，灵活注入对象",
  "全局模块和生命周期",
  "AOP 架构有什么好处？",
  "一网打尽 Nest 全部装饰器",
  "ExecutionContext：切换不同上下文",
  "Nest 如何自定义装饰器",
  "Metadata 和 Reflector",
  "Module 和 Provider 的循环依赖怎么处理？",
  "如何创建动态模块",
  "Nest 和 Express 的关系，如何切到 fastify",
  "Nest 的 Middleware",
  "RxJS 和 Interceptor",
  "内置 Pipe 和自定义 Pipe",
  "如何使用 ValidationPipe 验证 post 请求参数",
  "如何自定义 Exception Filter",
  "图解串一串 Nest 核心概念",
  "Express 如何使用 multer 实现文件上传",
  "Nest 如何使用 multer 实现文件上传",
  "大文件分片上传",
  "Nest 里如何打印日志？",
  "Nest 集成 Winston 管理日志",
  "通过 Desktop 学 Docker 也太简单了",
  "你的第一个 Dockerfile",
  "Nest 项目如何编写 Dockerfile",
  "提升 Dockerfile 水平的 5 个技巧",
  "Docker 是怎么实现的？",
  "为什么 Node 应用要用 PM2 来跑？",
  "快速入门 MySQL",
  "SQL 查询语句的所有语法和函数",
  "一对一、join 查询、级联方式",
  "一对多、多对多关系的表设计",
  "子查询和 EXISTS",
  "SQL 综合练习",
  "MySQL 的事务和隔离级别",
  "MySQL 的视图、存储过程和函数",
  "使用 Node 操作 MySQL 的两种方式",
  "快速掌握 TypeORM",
  "TypeORM 一对一的映射和关联 CRUD",
  "TypeORM 一对多的映射和关联 CRUD",
  "TypeORM 多对多的映射和关联 CRUD",
  "TypeORM 的全部命令",
  "TypeORM 知识点查缺补漏",
  "在 Nest 里集成 TypeORM",
  "快速入门 Redis",
  "在 Nest 里操作 Redis",
  "两种登录状态保存方式：JWT、Session",
  "Nest 里实现 Session 和 JWT",
  "MySQL + TypeORM + JWT 实现登录注册",
  "基于 ACL 实现权限控制",
  "基于 RBAC 实现权限控制",
  "基于 access_token 和 refresh_token 实现无感刷新登录状态",
  "如何动态读取不同环境的配置？",
  "为什么要使用 Docker Compose ？",
  "Docker 容器通信的最简单方式：桥接网络",
  "Docker 支持重启策略，是否还需要 PM2",
  "搭建私有 Docker 镜像仓库",
  "快速掌握 Nginx 的 2 大核心用法",
  "基于 Nginx 实现灰度系统",
  "Nginx 的全部配置",
  "基于 Redis 实现分布式 session",
  "Redis + 高德地图，实现附近的充电宝",
  "基于 Redis 实现王者荣耀段位排行榜",
  "用 Swagger 自动生成 api 文档",
  "使用 compodoc 生成文档",
  "Node 如何发邮件？",
  "实现基于邮箱验证码的登录",
  "使用阿里云的邮件和短信服务",
  "定时任务 + Redis 实现阅读量计数",
  "Nest 的 3 种定时任务",
  "Nest 实现 Server Sent Event 数据推送",
  "基于 sharp 实现 gif 压缩工具",
  "实现扫二维码登录",
  "Nest 的 REPL 模式",
  "使用 Prometheus 实现 Node 性能监控",
  "会议室预订系统：需求分析和原型图",
  "会议室预订系统：技术方案和数据库设计",
  "会议室预订系统：用户管理模块--用户注册",
  "会议室预订系统：用户管理模块--配置抽离、登录认证鉴权",
  "会议室预订系统：用户管理模块-- interceptor、修改信息接口",
  "会议室预订系统：用户管理模块--用户列表和分页查询",
  "会议室预订系统：用户管理模块-- swagger 接口文档",
  "会议室预订系统：用户管理模块-- 用户端登录注册页面",
  "会议室预订系统：用户管理模块-- 用户端信息修改页面",
  "会议室预订系统：用户管理模块-- 管理端用户列表页面",
  "会议室预订系统：用户管理模块-- 管理端信息修改页面",
  "会议室预订系统：会议室管理模块-后端开发",
  "会议室预订系统：会议室管理模块-管理端前端开发",
  "会议室预订系统：会议室管理模块-用户端前端开发",
  "会议室预订系统：预定管理模块-后端开发",
  "会议室预订系统：预定管理模块-前端开发",
  "会议室预订系统：统计管理模块-后端开发",
  "会议室预订系统：统计管理模块-前端开发",
  "会议室预订系统：项目部署和整体测试",
  "Nest 如何创建微服务？",
  "Nest 的 Monorepo 和 Library",
  "用 Etcd 实现微服务配置中心和注册中心",
  "Nest 集成 Etcd 做注册中心、配置中心",
  "使用 Nacos 做配置中心和注册中心",
  "使用 ZoopKeeper 做注册中心",
  "使用 Zuul 做配置中心和注册中心",
  "注册中心功能总结",
  "基于 gRPC 实现跨语言的微服务通信",
  "深入掌握 gRPC",
  "快速入门 ORM 框架 Prisma",
  "Prisma 的全部命令",
  "Primsa Client 的全部 api",
  "在 Nest 里集成 Prisma",
  "使用 Sequelize 做 ORM 框架",
  "TypeORM、Sequelize、Prisma 三大 ORM 框架对比",
  "为什么前端监控系统要用 RabbitMQ？",
  "快速掌握 RocketMQ",
  "快速掌握 Kafka",
  "消息队列选型",
  "基于 Redis 实现消息队列",
  "基于 Redis 实现分布式锁",
  "Redis 的 Stream 数据结构",
  "Redis 的布隆过滤器",
  "实现短链服务",
  "使用 passport 做身份认证",
  "实现单点登录",
  "BFF 层的作用",
  "什么是分布式架构",
  "Nest 如何写单元测试",
  "如何进行压力测试",
  "图解微服务架构",
  "电商系统：需求分析",
  "电商系统：数据库设计",
  "电商系统：微服务拆分",
  "电商系统：集成 RabbitMQ、Redis、Etcd",
  "电商系统：功能开发（上）",
  "电商系统：功能开发（下）",
  "电商系统：前端界面开发",
  "电商系统：Docker Compose 部署和整体测试",
  "基于 Redis 实现关注关系",
  "基于 Redis 实现 uv 计数",
  "面试题：说说 Redis 的应用场景",
  "为什么不使用 CacheManager 操作 Redis",
  "大众点评系统：需求分析和原型图",
  "大众点评系统：技术方案设计",
  "大众点评系统：后端开发",
  "大众点评系统：前端开发",
  "大众点评系统：项目部署和整体测试",
  "什么时候需要 WebSocket？",
  "用 Node.js 手写 WebSocket 协议",
  "MongoDB 快速入门",
  "在 Nest 里操作 MongoDB",
  "Nest 如何开发 WebSocket 服务？",
  "Redis + WebSocket 实时外卖员距离",
  "WebSocket 的面试题",
  "聊天室项目：需求分析",
  "聊天室项目：数据库设计",
  "聊天室项目：微服务拆分",
  "聊天室项目：功能开发（上）",
  "聊天室项目：功能开发（下）",
  "聊天室项目：前端界面开发",
  "聊天室项目：Docker Compose 部署",
  "GraphQL 快速入门",
  "Nest 如何开发 GraphQL 服务？",
  "Kafka 消息中间件和 RabbitMQ 有什么区别？",
  "GraphQL 的面试题",
  "教育平台：需求分析",
  "教育平台：数据库设计",
  "教育平台：微服务拆分",
  "教育平台：GraphQL 层设计",
  "教育平台：功能开发（上）",
  "教育平台：功能开发（下）",
  "为什么要用 ElasticSearch 做全文检索？",
  "部署一套 Kubenetes 环境",
  "ElasticSearch 和 MySQL 如何配合",
  "Node 里操作 ElasticSearch",
  "Nest 集成 ElasticSearch",
  "什么是 Kubenetes",
  "博客项目：需求分析",
  "博客项目：数据库设计",
  "博客项目：ORM 层开发",
  "博客系统：集成 ElasticSearch",
  "博客项目：功能开发",
  "博客项目：前端界面开发",
  "博客项目：Docker 部署",
  "博客项目：整体测试",
  "如何调试 Nest 源码？",
  "Nest IOC 实现原理",
  "手写 Nest 的 IOC 容器",
  "Nest AOP 实现原理",
  "Nest 的路由是怎么实现的",
  "Nest CLI 实现原理",
  "为什么公司里用 MySQL 比较多",
  "PostgreSQL 和 MySQL 的区别",
  "如何用 OAuth2.0 做三方授权",
  "实现三方扫码登录",
  "微信支付、支付宝支付",
  "面试题：sql 的执行流程",
  "面试题：mysql 索引优化",
  "面试题：redis 缓存雪崩、缓存击穿、缓存穿透",
  "小册总结"
]